#ifndef RUNMODE_CONTROL_H
#define	RUNMODE_CONTROL_H


//ビットパターンの定義

#define D_FLG_RUN_FORWARD_MODE		(0x0001)
#define D_FLG_RUN_TURN_RIGHT_MODE	(0x0002)
#define D_FLG_RUN_TURN_LEFT_MODE	(0x0004)
#define D_FLG_RUN_BACKARD_MODE		(0x0008)
#define D_FLG_RUN_STOP_MODE			(0x0010)

#define D_FLG_RUN_MODE_ALLPTN	( D_FLG_RUN_FORWARD_MODE | D_FLG_RUN_TURN_RIGHT_MODE | D_FLG_RUN_TURN_LEFT_MODE | D_FLG_RUN_BACKARD_MODE | D_FLG_RUN_STOP_MODE )




#endif	// RUNMODE_CONTROL_H